### ISSUE TITLE
Инвертированное отображение toggler

### ISSUE THREAD

**Issue by gheljenor** [yandex-ui/nanoislands#499]
Блок toggler рисуется инвертированным (во включенном состоянии показывает выкл и наоборот). Найти исходники стилей так и не смог. Вот такая заплатка исправляет проблему:

```css
._nb-small-toggler ._nb-toggler-view {
    background-position: 100% 0;
}

._nb-small-toggler > input:checked + ._nb-toggler-view {
    background-position: 0 0;
}

._nb-small-toggler ._nb-toggler-view-content {
    left: -100%;
}

._nb-small-toggler > input:checked + * > ._nb-toggler-view-content {
    left: 0%;
}
```
